name = "server"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL = "postgresql://neondb_owner:JSl3XbVsUw8W@ep-dark-breeze-a1h7xxid-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"
JWT_SECRET = "SUPERRRRRRRRRSECTETTEINGNAfksngkjqopfsjfjksnfsklj"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"